# run: conda env create --file environment.yml
name: jupyter-xprahtml5-proxy
channels:
  - conda-forge
dependencies:
  - jupyterlab=2
  - jupyterlab_server
  - jupyter_conda
  - pip
  - pip:
#      - xpra>=4.0.4
      - -r file:requirements.txt
